import React from "react"
import { RadioField } from "./Radio"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  RadioField,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13594",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      description: figma.string("Description"),
      isDisabled: figma.boolean("State", {
        true: "Disabled",
        false: "Default"
      }),
      isSelected: figma.boolean("Value Type", {
        true: "Checked",
        false: "Unchecked"
      }),
      hasDescription: figma.boolean("Has Description"),
    },
    example: (props) => (
      <RadioField
        label={props.label}
        description={props.hasDescription ? props.description : undefined}
        isDisabled={props.isDisabled}
        isSelected={props.isSelected}
      >
        {props.label}
      </RadioField>
    ),
  },
)
