import React from "react"
import { SelectField, SelectItem } from "./Select"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SelectField,
  "<FIGMA_INPUTS_SELECT_FIELD>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      description: figma.boolean("Has Description", {
        true: figma.string("Description"),
        false: undefined,
      }),
      isDisabled: figma.enum("State", { 
        Disabled: true,
        Default: false
      }),
      errorMessage: figma.enum("State", {
        Error: figma.string("Error"),
        Default: undefined
      }),
      value: figma.enum("Value Type", {
        Default: figma.string("Value"),
        Placeholder: undefined
      }),
      placeholder: figma.enum("Value Type", {
        Placeholder: figma.string("Value"),
        Default: "I am a placeholder..."
      }),
      defaultSelectedKey: figma.string("Value"),
    },
    example: (props) => (
      <SelectField
        label={props.label}
        description={props.description}
        isDisabled={props.isDisabled}
        errorMessage={props.errorMessage}
        value={props.value}
        placeholder={props.placeholder}
        defaultSelectedKey={props.defaultSelectedKey}
      >
        <SelectItem>{props.defaultSelectedKey}</SelectItem>
        <SelectItem>Option 2</SelectItem>
        <SelectItem>Option 3</SelectItem>
        <SelectItem>Option 4</SelectItem>
        <SelectItem>Option 5</SelectItem>
      </SelectField>
    ),
  },
)
