import React from "react"
import {
  Pagination,
  PaginationGap,
  PaginationList,
  PaginationNext,
  PaginationPage,
  PaginationPrevious,
} from "./Pagination"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  PaginationPage,
  "<FIGMA_PAGINATION_PAGINATION_PAGE>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Number"),
      current: figma.enum("State", {
        Current: true,
        "Current Hover": true,
        Default: false
      }),
      href: figma.string("Number"),
    },
    example: (props) => (
      <PaginationPage
        href={props.href}
        current={props.current}
      >
        {props.children}
      </PaginationPage>
    ),
  },
)

figma.connect(
  PaginationGap,
  "<FIGMA_PAGINATION_PAGINATION_GAP>",
  {
    props: {},
    example: () => <PaginationGap />,
  },
)

figma.connect(
  PaginationPrevious,
  "<FIGMA_PAGINATION_PAGINATION_PREVIOUS>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      href: figma.enum("State", { 
        Default: "?previous", 
        Hover: "?previous",
        Disabled: undefined
      }),
    },
    example: (props) => (
      <PaginationPrevious href={props.href} />
    ),
  },
)

figma.connect(
  PaginationNext,
  "<FIGMA_PAGINATION_PAGINATION_NEXT>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      href: figma.enum("State", { 
        Default: "?next", 
        Hover: "?next",
        Disabled: undefined
      }),
    },
    example: (props) => (
      <PaginationNext href={props.href} />
    ),
  },
)

figma.connect(
  PaginationList,
  "<FIGMA_PAGINATION_PAGINATION_LIST>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children("Pagination Page"),
    },
    example: (props) => (
      <PaginationList>
        {props.children}
      </PaginationList>
    ),
  },
)

figma.connect(
  Pagination,
  "<FIGMA_PAGINATION_PAGINATION>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children("Pagination Previous"),
    },
    example: (props) => (
      <Pagination>
        {props.children}
      </Pagination>
    ),
  },
)
