import React from "react"
import { Image, Picture, PictureSource } from "./Image"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Image,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13526",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      alt: figma.string("Alt Text"),
      src: figma.string("Image Source"),
      aspectRatio: figma.enum("Aspect Ratio", {
        "1:1": "1-1",
        "16:9": "16-9",
        "4:3": "4-3",
        "Fill": "fill",
        "Natural": "natural"
      }),
      size: figma.enum("Size", {
        "Small": "small",
        "Medium": "medium",
        "Large": "large",
        "Fill": "fill",
        "Natural": "natural"
      }),
      variant: figma.enum("Variant", {
        "Default": "default",
        "Rounded": "rounded"
      }),
    },
    example: (props) => (
      <Image
        alt={props.alt}
        src={props.src}
        aspectRatio={props.aspectRatio}
        size={props.size}
        variant={props.variant}
      />
    ),
  },
)

figma.connect(
  Picture,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13526",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children("Picture Source"),
    },
    example: (props) => (
      <Picture>
        {props.children}
      </Picture>
    ),
  },
)

figma.connect(
  PictureSource,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13526",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      srcSet: figma.string("Source Set"),
      media: figma.string("Media Query"),
    },
    example: (props) => (
      <PictureSource
        srcSet={props.srcSet}
        media={props.media}
      />
    ),
  },
)
