import React from "react"
import { Accordion, AccordionItem } from "./Accordion"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Accordion,
  "<FIGMA_ACCORDION_ACCORDION>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children("Accordion Item"),
    },
    example: (props) => (
      <Accordion>
        {props.children}
      </Accordion>
    ),
  },
)

figma.connect(
  AccordionItem,
  "<FIGMA_ACCORDION_ACCORDION_ITEM>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      title: figma.string("Title"),
      children: figma.string("Content"),
      isExpanded: figma.enum("State", {
        Open: true,
        Closed: false
      }),
      isDisabled: figma.boolean("Disabled"),
    },
    example: (props) => (
      <AccordionItem
        title={props.title}
        isExpanded={props.isExpanded}
        isDisabled={props.isDisabled}
      >
        {props.children}
      </AccordionItem>
    ),
  },
)
