import React from "react"
import { Tab, Tabs, TabList, TabPanel } from "./Tab"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tab,
  "<FIGMA_TABS_TAB>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Label"),
    },
    example: (props) => (
      <Tab id={props.children}>
        {props.children}
      </Tab>
    ),
  },
)

figma.connect(
  Tabs,
  "<FIGMA_TABS_TABS>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children("Tab"),
    },
    example: (props) => (
      <Tabs>
        <TabList>{props.children}</TabList>
        <TabPanel id="match-each-tab">Some content</TabPanel>
      </Tabs>
    ),
  },
)
