import React from "react"
import { IconButton, DestructiveIconButton } from "./IconButton"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  IconButton,
  "<FIGMA_BUTTONS_ICON_BUTTON>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      icon: figma.instance("Icon"),
      isDisabled: figma.enum("State", {
        Disabled: true,
        Default: false
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large"
      }),
      variant: figma.enum("Variant", {
        Primary: "primary",
        Neutral: "neutral",
        Subtle: "subtle"
      }),
    },
    example: (props) => (
      <IconButton
        aria-label="Write a nice description of the action."
        icon={props.icon}
        isDisabled={props.isDisabled}
        size={props.size}
        variant={props.variant}
      />
    ),
  },
)

figma.connect(
  DestructiveIconButton,
  "<FIGMA_BUTTONS_ICON_BUTTON>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      icon: figma.instance("Icon"),
      isDisabled: figma.enum("State", {
        Disabled: true,
        Default: false
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large"
      }),
    },
    example: (props) => (
      <DestructiveIconButton
        aria-label="Write a nice description of the action."
        icon={props.icon}
        isDisabled={props.isDisabled}
        size={props.size}
      />
    ),
  },
)
