import React from "react"
import { Table } from "./Table"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Table,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13630",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      bleed: figma.boolean("Bleed"),
      dense: figma.boolean("Dense"),
      grid: figma.boolean("Grid"),
      striped: figma.boolean("Striped"),
    },
    example: (props) => (
      <Table
        bleed={props.bleed}
        dense={props.dense}
        grid={props.grid}
        striped={props.striped}
      >
        {/* Table content will be generated by the plugin */}
      </Table>
    ),
  },
)
