import React from "react"
import { SliderField } from "./Slider"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SliderField,
  "<FIGMA_INPUTS_SLIDER_FIELD>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      description: figma.boolean("Has Description", {
        true: figma.string("Description"),
        false: undefined,
      }),
      isDisabled: figma.enum("State", { 
        Disabled: true,
        Default: false
      }),
    },
    example: (props) => (
      <SliderField
        label={props.label}
        description={props.description}
        isDisabled={props.isDisabled}
        showOutput
      />
    ),
  },
)
