import React from "react"
import {
  Menu,
  MenuDescription,
  MenuHeader,
  MenuHeading,
  MenuItem,
  MenuLabel,
  MenuSeparator,
  MenuShortcut,
} from "./Menu"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Menu,
  "<FIGMA_MENU_MENU>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children([
        "Menu Header",
        "Menu Separator",
        "Menu Section",
        "Menu Item",
      ]),
    },
    example: (props) => (
      <Menu>
        {props.children}
      </Menu>
    ),
  },
)

figma.connect(
  MenuHeading,
  "<FIGMA_MENU_MENU_HEADING>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children("Text Strong"),
    },
    example: (props) => (
      <MenuHeading>
        {props.children}
      </MenuHeading>
    ),
  },
)

figma.connect(
  MenuShortcut,
  "<FIGMA_MENU_MENU_SHORTCUT>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Shortcut"),
    },
    example: (props) => (
      <MenuShortcut>
        {props.children}
      </MenuShortcut>
    ),
  },
)

figma.connect(
  MenuItem,
  "<FIGMA_MENU_MENU_ITEM>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      icon: figma.boolean("Has Icon", {
        true: figma.instance("Icon"),
        false: undefined,
      }),
      description: figma.boolean("Has Description", {
        true: figma.string("Description"),
        false: undefined,
      }),
      shortcut: figma.boolean("Has Shortcut", {
        true: figma.children("Menu Shortcut"),
        false: undefined,
      }),
      children: figma.string("Label"),
    },
    example: (props) => (
      <MenuItem>
        {props.icon}
        <MenuLabel>{props.children}</MenuLabel>
        {props.shortcut}
        {props.description && <MenuDescription>{props.description}</MenuDescription>}
      </MenuItem>
    ),
  },
)

figma.connect(
  MenuHeader,
  "<FIGMA_MENU_MENU_HEADER>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      header: figma.children("Text Strong"),
      subhead: figma.children("Text Small"),
    },
    example: (props) => (
      <MenuHeader>
        {props.subhead}
        {props.header}
      </MenuHeader>
    ),
  },
)

figma.connect(
  MenuSeparator,
  "<FIGMA_MENU_MENU_SEPARATOR>",
  {
    props: {},
    example: () => <MenuSeparator />,
  },
)
