import React from "react"
import { Checkbox, CheckboxField, CheckboxGroup } from "./Checkbox"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  CheckboxField,
  "<FIGMA_INPUTS_CHECKBOX_FIELD>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      description: figma.boolean("Has Description", {
        true: figma.string("Description"),
        false: undefined,
      }),
      isSelected: figma.enum("Value Type", {
        Checked: true,
        Unchecked: false
      }),
      isIndeterminate: figma.enum("Value Type", {
        Indeterminate: true,
        Checked: false,
        Unchecked: false
      }),
      isDisabled: figma.enum("State", {
        Disabled: true,
        Default: false
      }),
    },
    example: (props) => (
      <CheckboxField
        label={props.label}
        description={props.description}
        isSelected={props.isSelected}
        isIndeterminate={props.isIndeterminate}
        isDisabled={props.isDisabled}
      >
        {props.label}
      </CheckboxField>
    ),
  },
)

figma.connect(
  CheckboxGroup,
  "<FIGMA_INPUTS_CHECKBOX_GROUP>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children(["Checkbox Field"]),
      label: figma.string("Label"),
      description: figma.boolean("Has Description", {
        true: figma.string("Description"),
        false: undefined,
      }),
      errorMessage: figma.string("Error Message"),
    },
    example: (props) => (
      <CheckboxGroup
        label={props.label}
        description={props.description}
        errorMessage={props.errorMessage}
      >
        {props.children}
      </CheckboxGroup>
    ),
  },
)

figma.connect(
  Checkbox,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4039%3A13063",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      // Basic Checkbox component - can be expanded with additional properties
      // as needed for your Figma design system
    },
    example: (props) => (
      <Checkbox>
        {/* Checkbox icons are built-in */}
      </Checkbox>
    ),
  },
)
