import React from "react"
import { Logo } from "./Logo"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Logo,
  "<FIGMA_LOGO_LOGO>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      // Basic Logo component - can be expanded with additional properties
      // as needed for your Figma design system
    },
    example: (props) => (
      <Logo>
        {/* Logo SVG content is built-in */}
      </Logo>
    ),
  },
)
