import React from "react"
import { Avatar, AvatarButton, AvatarBlock, AvatarGroup } from "./Avatar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Avatar,
  "<FIGMA_AVATARS_AVATAR>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      square: figma.enum("Shape", {
        Square: true,
        Circle: false
      }),
      initials: figma.enum("Type", {
        Initial: figma.string("Initials"),
        Image: undefined
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large"
      }),
      src: figma.enum("Type", {
        Image: figma.string("Image Source"),
        Initial: undefined
      }),
      alt: figma.string("Alt Text"),
    },
    example: (props) => (
      <Avatar
        square={props.square}
        initials={props.initials}
        size={props.size}
        src={props.src}
        alt={props.alt}
      />
    ),
  },
)

figma.connect(
  AvatarButton,
  "<FIGMA_AVATARS_AVATAR>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      square: figma.enum("Shape", {
        Square: true,
        Circle: false
      }),
      initials: figma.enum("Type", {
        Initial: figma.string("Initials"),
        Image: undefined
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large"
      }),
      src: figma.enum("Type", {
        Image: figma.string("Image Source"),
        Initial: undefined
      }),
      alt: figma.string("Alt Text"),
    },
    example: (props) => (
      <AvatarButton
        square={props.square}
        initials={props.initials}
        size={props.size}
        src={props.src}
        alt={props.alt}
      />
    ),
  },
)

figma.connect(
  AvatarBlock,
  "<FIGMA_AVATARS_AVATAR_BLOCK>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      title: figma.string("Title"),
      description: figma.string("Description"),
      children: figma.children("Avatar"),
    },
    example: (props) => (
      <AvatarBlock
        title={props.title}
        description={props.description}
      >
        {props.children}
      </AvatarBlock>
    ),
  },
)

figma.connect(
  AvatarGroup,
  "<FIGMA_AVATARS_AVATAR_GROUP>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      spacing: figma.enum("Spacing", {
        Overlap: "negative-200",
        Spaced: "100",
        Default: "200"
      }),
      children: figma.children("Avatar"),
      max: figma.number("Max Count"),
    },
    example: (props) => (
      <AvatarGroup
        spacing={props.spacing}
        max={props.max || 3}
      >
        {props.children}
      </AvatarGroup>
    ),
  },
)
