import React from "react"
import { Icon } from "./Icon"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Icon,
  "<FIGMA_ICONS_BASE>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        "14": "14",
        "16": "16",
        "20": "20",
        "24": "24",
        "32": "32",
        "40": "40",
        "48": "48"
      }),
      children: figma.children("SVG Path"), // SVG content as children
    },
    example: (props) => (
      <Icon size={props.size}>
        {props.children}
      </Icon>
    ),
  },
)
