import React from "react"
import { Navigation, NavigationButton, NavigationPill } from "./Navigation"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Navigation,
  "<FIGMA_NAVIGATION_NAVIGATION_PILL_LIST>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children("Navigation Pill"),
      direction: figma.enum("Direction", {
        Row: "row",
        Column: "column",
      }),
    },
    example: (props) => (
      <Navigation direction={props.direction}>
        {props.children}
      </Navigation>
    ),
  },
)

figma.connect(
  NavigationPill,
  "<FIGMA_NAVIGATION_NAVIGATION_PILL>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Label"),
      isSelected: figma.enum("State", {
        Active: true,
        Default: false,
        Hover: false,
      }),
    },
    example: (props) => (
      <NavigationPill isSelected={props.isSelected}>
        {props.children}
      </NavigationPill>
    ),
  },
)

figma.connect(
  Navigation,
  "<FIGMA_NAVIGATION_NAVIGATION_BUTTON_LIST>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children("Navigation Button"),
      direction: figma.enum("Direction", {
        Row: "row",
        Column: "column",
      }),
    },
    example: (props) => (
      <Navigation direction={props.direction}>
        {props.children}
      </Navigation>
    ),
  },
)

figma.connect(
  NavigationButton,
  "<FIGMA_NAVIGATION_NAVIGATION_BUTTON>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Label"),
      icon: figma.boolean("Has Icon", {
        true: figma.instance("Icon"),
        false: undefined,
      }),
      isSelected: figma.enum("State", {
        Active: true,
        Default: false,
        Hover: false,
      }),
    },
    example: (props) => (
      <NavigationButton
        icon={props.icon}
        isSelected={props.isSelected}
      >
        {props.children}
      </NavigationButton>
    ),
  },
)
