import React from "react"
import { Button } from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4185%3A3778",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      iconStart: figma.instance("Icon Start"),
      iconEnd: figma.instance("Icon End"),
      hasIconStart: figma.boolean("Has Icon Start"),
      hasIconEnd: figma.boolean("Has Icon End"),
      variant: figma.enum("Variant", {
        Primary: "primary",
        Neutral: "neutral",
        Subtle: "subtle",
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "iconEnd": figma.instance('Icon End'),
      // "hasIconEnd": figma.boolean('Has Icon End'),
      // "hasIconStart": figma.boolean('Has Icon Start'),
      // "iconStart": figma.instance('Icon Start'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Disabled": "disabled"
      // })
    },
    example: (props) => (
      <Button
        label={props.label}
        size={props.size}
        iconStart={props.iconStart}
        iconEnd={props.iconEnd}
        hasIconStart={props.hasIconStart}
        hasIconEnd={props.hasIconEnd}
        variant={props.variant}
      />
    ),
  },
)
