import React from "react"
import { Tooltip } from "./Tooltip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tooltip,
  "<FIGMA_TOOLTIP_TOOLTIP>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Text"),
    },
    example: (props) => (
      <Tooltip>
        {props.children}
      </Tooltip>
    ),
  },
)
