import React from "react"
import { ListBox, ListBoxItem } from "./ListBox"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ListBox,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13518",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children("ListBox Item"),
    },
    example: (props) => (
      <ListBox>
        {props.children}
      </ListBox>
    ),
  },
)

figma.connect(
  ListBoxItem,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13518",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Text"),
    },
    example: (props) => (
      <ListBoxItem>
        {props.children}
      </ListBoxItem>
    ),
  },
)
