import React from "react"
import { Notification } from "./Notification"
import { Text, TextStrong } from "../Text/Text"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Notification,
  "<FIGMA_NOTIFICATION_NOTIFICATION>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      title: figma.string("Title"),
      icon: figma.boolean("Has Icon", {
        true: figma.instance("Icon"),
        false: undefined,
      }),
      isDismissible: figma.boolean("Dismissible"),
      button: figma.children("Button"),
      body: figma.string("Body"),
      variant: figma.enum("Variant", {
        Message: "message",
        Alert: "alert",
      }),
    },
    example: (props) => (
      <Notification
        icon={props.icon}
        isDismissible={props.isDismissible}
        variant={props.variant}
      >
        <TextStrong>{props.title}</TextStrong>
        <Text>{props.body}</Text>
        {props.button}
      </Notification>
    ),
  },
)
