import React from "react"
import {
  Dialog,
  DialogBody,
  DialogClose,
  DialogModal,
  DialogTitle,
  DialogDescription,
  DialogTrigger,
  DialogButton,
} from "./Dialog"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Dialog,
  "<FIGMA_DIALOG_DIALOG_BODY>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      type: figma.enum("Type", { 
        Card: "card", 
        Sheet: "sheet" 
      }),
      body: figma.string("Body"),
      heading: figma.string("Heading"),
      buttons: figma.children("Button Group"),
    },
    example: (props) => (
      <Dialog type={props.type}>
        <DialogClose onPress={() => {}} />
        <DialogTitle>{props.heading}</DialogTitle>
        <DialogBody>{props.body}</DialogBody>
        {props.buttons}
      </Dialog>
    ),
  },
)

figma.connect(
  Dialog,
  "<FIGMA_DIALOG_DIALOG>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children("Dialog Body"),
    },
    example: (props) => (
      <DialogModal isDismissable isOpen={true} onOpenChange={() => {}}>
        {props.children}
      </DialogModal>
    ),
  },
)

figma.connect(
  DialogTitle,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13568",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Text"),
    },
    example: (props) => (
      <DialogTitle>
        {props.children}
      </DialogTitle>
    ),
  },
)

figma.connect(
  DialogDescription,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13568",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Text"),
    },
    example: (props) => (
      <DialogDescription>
        {props.children}
      </DialogDescription>
    ),
  },
)

figma.connect(
  DialogBody,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13568",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children(["Dialog Title", "Dialog Description", "Text"]),
      bleed: figma.boolean("Bleed"),
    },
    example: (props) => (
      <DialogBody bleed={props.bleed}>
        {props.children}
      </DialogBody>
    ),
  },
)

figma.connect(
  DialogTrigger,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13568",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children("Button"),
    },
    example: (props) => (
      <DialogTrigger>
        {props.children}
      </DialogTrigger>
    ),
  },
)

figma.connect(
  DialogButton,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13568",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      variant: figma.enum("Variant", {
        Primary: "primary",
        Neutral: "neutral",
        Subtle: "subtle"
      }),
      icon: figma.instance("Icon"),
      children: figma.children("Dialog"),
    },
    example: (props) => (
      <DialogButton
        label={props.label}
        variant={props.variant}
        icon={props.icon}
      >
        {props.children}
      </DialogButton>
    ),
  },
)
