import React from "react"
import { Card } from "./Cards"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Card,
  "<FIGMA_CARDS_CARD>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      align: figma.enum("Align", {
        Start: "start",
        Center: "center",
        End: "end"
      }),
      direction: figma.enum("Direction", {
        Horizontal: "horizontal",
        Vertical: "vertical"
      }),
      variant: figma.enum("Variant", {
        Default: "default",
        Stroke: "stroke",
        Brand: "brand"
      }),
      padding: figma.enum("Padding", {
        "600": "600",
        "800": "800"
      }),
      asset: figma.instance("Asset"),
      children: figma.children(["Text", "Button", "Image"]),
    },
    example: (props) => (
      <Card
        align={props.align}
        direction={props.direction}
        variant={props.variant}
        padding={props.padding}
        asset={props.asset}
      >
        {props.children}
      </Card>
    ),
  },
)
