import React from "react"
import { Link } from "./Link"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Link,
  "<FIGMA_TEXT_TEXT_LINK>",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Text"),
      href: figma.string("Text"), // Using text as href placeholder
    },
    example: (props) => (
      <Link href={props.href || "#"}>
        {props.children}
      </Link>
    ),
  },
)
