import React from "react"
import {
  Fieldset,
  Legend,
  FieldGroup,
  Form,
  Field,
  Label,
  Description,
  FieldError,
  Keyboard,
} from "./Fieldset"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Fieldset,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13568",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children(["Legend", "Field", "FieldGroup"]),
    },
    example: (props) => (
      <Fieldset>
        {props.children}
      </Fieldset>
    ),
  },
)

figma.connect(
  Legend,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13568",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Text"),
    },
    example: (props) => (
      <Legend>
        {props.children}
      </Legend>
    ),
  },
)

figma.connect(
  FieldGroup,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13568",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children("Field"),
    },
    example: (props) => (
      <FieldGroup>
        {props.children}
      </FieldGroup>
    ),
  },
)

figma.connect(
  Form,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13568",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children(["Fieldset", "Field", "FieldGroup"]),
      singleLine: figma.boolean("Single Line"),
    },
    example: (props) => (
      <Form singleLine={props.singleLine}>
        {props.children}
      </Form>
    ),
  },
)

figma.connect(
  Field,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13568",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.children(["Label", "Description", "FieldError"]),
    },
    example: (props) => (
      <Field>
        {props.children}
      </Field>
    ),
  },
)

figma.connect(
  Label,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13568",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Text"),
    },
    example: (props) => (
      <Label>
        {props.children}
      </Label>
    ),
  },
)

figma.connect(
  Description,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13568",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Text"),
    },
    example: (props) => (
      <Description>
        {props.children}
      </Description>
    ),
  },
)

figma.connect(
  FieldError,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13568",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Text"),
    },
    example: (props) => (
      <FieldError>
        {props.children}
      </FieldError>
    ),
  },
)

figma.connect(
  Keyboard,
  "https://www.figma.com/design/QkCVMrKpIW8zdiI05xNLho/Simple-Design-System?node-id=4049%3A13568",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Text"),
    },
    example: (props) => (
      <Keyboard>
        {props.children}
      </Keyboard>
    ),
  },
)
